### ISSUE TITLE
Add linting to blueprint

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/broccoli-plugin-kit#8]

**Comment by trentmwillis** [comment]
Should we use [broccoli-lint-eslint](https://github.com/ember-cli/broccoli-lint-eslint) for the linting?

**Comment by rwjblue** [comment]
Ya, seems good to me...

**Comment by rwjblue** [comment]
Though if we are already using `mocha` we might as well just use `mocha-eslint` directly?

**Comment by trentmwillis** [comment]
Hmm, I'll investigate that. I guess it depends on when we want the linting done (build time vs test time).

**Comment by rwjblue** [comment]
Yeah, it would be good to do both.  broccoli-lint-eslint would allow us to both log console warnings and emit failing / passing tests (via the test generator), this roughly emulates what an ember-cli app does, so maybe that is the right path here...

**Comment by trentmwillis** [comment]
I have a potential implementation in https://github.com/ember-engines/broccoli-dependency-funnel/pull/10. If that looks good, we can merge there and then extract it into the blueprint here.

**Comment by trentmwillis** [comment]
So eslint only supports Node `>=4`. I think this means we should just do linting in tests and not run those tests in Node `0.12`.

**Comment by rwjblue** [comment]
@trentmwillis - We have to use eslint@2 and broccoli-lint-eslint@2 for Node 0.12 support.
